test: test_bindings.pickle parser.py scanner.py bindings.py
	python3 testerator.py run --input test_bindings.pickle

db_test: test_bindings.pickle parser.py scanner.py bindings.py
	python3 -m pdb testerator.py run --input test_bindings.pickle

