# Students:  DO NOT EDIT THIS FILE


import typing


class Coord(typing.NamedTuple):
    col: int
    line: int

    def __str__(self):
        return f"{self.line}:{self.col}"


class Token(typing.NamedTuple):
    kind: str
    value: str
    coord: Coord

    def __str__(self):
        return f"{self.kind}({self.value}) at {self.coord}"


# These are the tokens that are made of punctuation characters.
punctuation: list[str] = [
    ":",
    ",",
    "!=",
    "&",
    "*",
    "/",
    "%",
    "<=",
    "<",
    ">=",
    ">",
    "==",
    "|",
    "=",
    "+",
    "-",
    "[",
    "]",
    "{",
    "}",
    "(",
    ")",
]

# These are the keyword tokens.
keywords: list[str] = [
    "and",
    "bool",
    "call",
    "else",
    "false",
    "func",
    "if",
    "int",
    "length",
    "not",
    "or",
    "print",
    "return",
    "true",
    "var",
    "while",
]

# These are all the kinds of tokens
kinds: list[str] = ["ID", "INT"] + punctuation + keywords
